title: SVGExtended 
tagline: Extension of SVG support in Processing.
description: Extension of SVG support in Processing.

show_downloads: true
show_fork: true
lib_name: SVGExtended
owner_name: Rea-lity-Tech

google-tracking-id: "UA-73807553-1"

lang: "en"
author: "SASU RealityTech"

keywords: "augmented reality, soby, processing, java"
favicon: "/img/favicon-bug.ico"
404-img: "/img/labtocat.png"

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/bois2.jpg"

# Background credits
# https://www.flickr.com/photos/postneutralicus/30839878074/in/photostream/


me-img: "/img/logo-no-text.svg"

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"


email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
google-plus-share: True
tumblr-share: False
reddit-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False


syntax-highlight: True

email: "laviole@rea.lity.tech"

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/rea_lity_tech/"
  - title: "github"
    url: "https://github.com/poqudrof"


404-img: "/img/racoon.jpg"


pages_list:
  Activity: 'activity'
  Contact: 'contact'

  #Timeline: 'timeline'


# Exclusion list from the generated _site

exclude: ["LICENSE", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "ressources", "Gemfile", "Gemfile.lock", "deploy", "build-test", "build-prod"]


# Pagination path
paginate_path: "blog/page:num/"


sass:
  style: compressed

gems:
  - jekyll-paginate

markdown:    kramdown

